#pragma once
#include "ImageProcessor.h"
#include "Factory.h"
#include "Notifier.h"
#include "Runnable.h"
#include "FrameSource.h"
#include "PipelineConfiguration.h"
#include "FrameSourceFactory.h"
#include <any>
#include <opencv2/core/mat.hpp>
#include <nlohmann/json.hpp>

/**
 * Responsibility: allows to control the pipeline from the outside (for example from a GUI).
 * Image processors can be registered and loaded into the pipeline
 * A frame source can be loaded (images and videos supported).
 * The image processors loaded into the pipeline can be configured.
 * Debug images of each image processor can be retrieved.
 */
class PipelineController: public Notifier, Runnable
{
public:

    /**
     * Default constructor
     */
    PipelineController();

    /**
     * Constructor with frame source factory injection for testing purposes.
     * @param frameSourceFactory frame source factory dependency to be injected.
     */
    explicit PipelineController(std::unique_ptr<FrameSourceFactory> frameSourceFactory);

    /**
     * Configure pipeline using pipeline configuration.
     * @param configuration pipeline configuration
     */
    void loadPipeline(const PipelineConfiguration& configuration);

    /**
    * Configure pipeline using pipeline configuration json.
    * @param configurationFile the configuration json.
    */
    void loadPipelineFromJson(const nlohmann::json& configurationFile);

    /**
    * Configure pipeline using pipeline configuration json file.
    * @param configurationFile the configuration json file.
    */
    void loadPipelineFromJsonFile(const std::string& path);

    /**
     * Load the image to be processed through the pipeline
     * @param path of the image
     */
    void loadFrameSourceFrom(const std::string& path);

    /**
     * Retrieve current pipeline configuration.
     * @return current pipeline configuration.
     */
    PipelineConfiguration getPipelineConfiguration() const;

    /**
     * Set frame source index to be loaded when the pipeline processor is fired
     * @param index of the image to be processed through the pipeline
     */
    void setFrameSourceIndex(unsigned int index);

    /**
     * Configure the parameters of an image processor
     * @param index the index of the processor in the pipeline
     * @param configuration the parameters to be configured in json format
     */
    void configureProcessor(unsigned int index, const Configuration& configuration);

    /**
     * Get the parameters of an image processor
     * @param processorIndex index of the processor to get the parameters
     * @return the parameters parameters of the image processor
     */
    Parameters getProcessorParameters(unsigned int processorIndex) const;

    /**
     * Start the loaded image processing through the pipeline
     */
    void firePipelineProcessing();

    /**
     * Add an image processor to the back of the pipeline
     * @param imageProcessor the processor to be added
     */
    void addImageProcessor(std::unique_ptr<ImageProcessor> imageProcessor);

    /**
     * Get loaded image
     * @return loaded image
     */
    cv::Mat getCurrentLoadedImage();

    /**
     * Get a debug image generated by a specific image processor
     * @param processorIndex the index of the processor in the pipeline
     * @return
     */
    cv::Mat getDebugImageFrom(unsigned int processorIndex);

    /**
     * Register an image processor in order to used when creating pipelines by name
     * @tparam T Processor type
     * @param processorName name to register the processor
     */
    template <typename T>
    void registerImageProcessor(const std::string& processorName)
    {
        imageProcessorFactory.registerMaker<T>(processorName);
    }

    /**
     * Get frame source total frames
     * @return frame source total frames
     */
    unsigned int getTotalFrames() const;


private:
    std::unique_ptr<FrameSourceFactory> frameSourceFactory;
    std::vector<std::unique_ptr<ImageProcessor>> imageProcessors;
    Factory<ImageProcessor> imageProcessorFactory;
    cv::Mat currentImage;
    std::unique_ptr<FrameSource> frameSource;
    unsigned int frameSourceIndex;
    std::string frameSourcePath;

    void runIteration() override;
};